version: '3'
services:
  cedar-microservice:
    container_name: cedar-microservice
    image: "metadatacenter/cedar-microservice"
    build: ../cedar-microservice
  schema-server:
    depends_on:
        - cedar-microservice
    container_name: schema-server
    image: "metadatacenter/cedar-schema-server"
    build: ../cedar-schema-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_PORT_SCHEMA}:${CEDAR_PORT_SCHEMA}"
    volumes:
      - ${CEDAR_DOCKER_HOME}/log/cedar-schema-server/:/cedar/log/cedar-schema-server/
    environment:
      - CEDAR_HOST
      - CEDAR_KEYCLOAK_CLIENT_ID
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_LD_USER_BASE
      - CEDAR_PORT_SCHEMA
  user-server:
    depends_on:
        - cedar-microservice
    container_name: user-server
    image: "metadatacenter/cedar-user-server"
    build: ../cedar-user-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_PORT_USER}:${CEDAR_PORT_USER}"
    volumes:
      - ${CEDAR_DOCKER_HOME}/log/cedar-user-server/:/cedar/log/cedar-user-server/
    environment:
      - CEDAR_HOST
      - CEDAR_KEYCLOAK_CLIENT_ID
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_LD_USER_BASE
      - CEDAR_PORT_USER
  submission-server:
    depends_on:
        - cedar-microservice
    container_name: submission-server
    image: "metadatacenter/cedar-submission-server"
    build: ../cedar-submission-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_PORT_SUBMISSION}:${CEDAR_PORT_SUBMISSION}"
    volumes:
      - ${CEDAR_DOCKER_HOME}/log/cedar-submission-server/:/cedar/log/cedar-submission-server/
    environment:
      - CEDAR_HOST
      - CEDAR_KEYCLOAK_CLIENT_ID
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_LD_USER_BASE
      - CEDAR_PORT_SUBMISSION
      - CEDAR_NCBI_SRA_FTP_PASSWORD
  group-server:
    depends_on:
        - cedar-microservice
    container_name: group-server
    image: "metadatacenter/cedar-group-server"
    build: ../cedar-group-server
    networks:
      - cedarnet
    ports:
      - "${CEDAR_PORT_GROUP}:${CEDAR_PORT_GROUP}"
    volumes:
      - ${CEDAR_DOCKER_HOME}/log/cedar-group-server/:/cedar/log/cedar-group-server/
    environment:
      - CEDAR_HOST
      - CEDAR_KEYCLOAK_CLIENT_ID
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_NEO4J_USER_NAME
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_LD_USER_BASE
      - CEDAR_EVERYBODY_GROUP_NAME
      - CEDAR_PORT_GROUP


networks:
  cedarnet:
    external:
      name: cedarnet