version: '3'
services:
  mongo:
    container_name: mongo
    image: "metadatacenter/cedar-mongo"
    build: ../cedar-mongo
    networks:
      - cedarnet
    ports:
      - "${CEDAR_PORT_MONGO}:27017"
    volumes:
      - ${CEDAR_DOCKER_HOME}/data/mongo/:/data/db
      - ${CEDAR_DOCKER_HOME}/log/mongo/:/data/log
    environment:
      - CEDAR_MONGO_ROOT_USER_NAME
      - CEDAR_MONGO_ROOT_USER_PASSWORD
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_APP_DATABASE_NAME
      - CEDAR_LD_USER_BASE
      - CEDAR_HOST
      - CEDAR_ADMIN_USER_API_KEY

  redis-persistent:
    container_name: redis-persistent
    image: "metadatacenter/cedar-redis-persistent"
    build: ../cedar-redis-persistent
    networks:
      - cedarnet
    ports:
      - ${CEDAR_REDIS_PERSISTENT_PORT}:6379
    volumes:
      - ${CEDAR_DOCKER_HOME}/data/redis/:/data
      - ${CEDAR_DOCKER_HOME}/log/redis/:/log
    sysctls:
      - net.core.somaxconn=512

  postgres:
    container_name: postgres
    image: "metadatacenter/cedar-postgres"
    build: ../cedar-postgres
    networks:
      - cedarnet
    ports:
      - ${CEDAR_POSTGRES_PORT}:5445
    volumes:
      - ${CEDAR_DOCKER_HOME}/data/postgres/:/var/lib/postgresql/data
      - ${CEDAR_DOCKER_HOME}/log/postgres/:/var/log/postgresql
    environment:
      - CEDAR_POSTGRES_USER
      - CEDAR_POSTGRES_PASSWORD

  keycloak:
    container_name: keycloak
    image: "metadatacenter/cedar-keycloak"
    build: ../cedar-keycloak
    networks:
      - cedarnet
    ports:
      - ${CEDAR_KEYCLOAK_PORT}:8080
    volumes:
      - ${CEDAR_DOCKER_HOME}/log/keycloak:/opt/jboss/keycloak/standalone/log
    extra_hosts:
      - "resource.${CEDAR_HOST}:${CEDAR_DOCKER_HOST}"
    environment:
      - CEDAR_POSTGRES_USER
      - CEDAR_POSTGRES_PASSWORD
      - CEDAR_POSTGRES_PORT
      - CEDAR_POSTGRES_HOST
      - CEDAR_KEYCLOAK_ADMIN_USER
      - CEDAR_KEYCLOAK_ADMIN_PASSWORD
      - CEDAR_RESOURCE_SERVER_USER_CALLBACK_URL
      - CEDAR_RESOURCE_SERVER_ADMIN_CALLBACK_URL
      - CEDAR_LD_USER_BASE
      - CEDAR_ADMIN_USER_API_KEY
      - CEDAR_KEYCLOAK_CLIENT_ID
      - CEDAR_HOST

  elasticsearch:
    container_name: elasticsearch
    image: "metadatacenter/cedar-elasticsearch"
    build: ../cedar-elasticsearch
    networks:
      - cedarnet
    ports:
      - ${CEDAR_ELASTICSEARCH_REST_PORT}:9200
    volumes:
      - ${CEDAR_DOCKER_HOME}/data/elasticsearch:/usr/share/elasticsearch/data
      - ${CEDAR_DOCKER_HOME}/log/elasticsearch:/usr/share/elasticsearch/logs

  neo4j:
    container_name: neo4j
    image: "metadatacenter/cedar-neo4j"
    build: ../cedar-neo4j
    networks:
      - cedarnet
    ports:
      - ${CEDAR_NEO4J_REST_PORT}:7474
      - ${CEDAR_NEO4J_BOLT_PORT}:7687
    volumes:
      - ${CEDAR_DOCKER_HOME}/data/neo4j/:/data
      - ${CEDAR_DOCKER_HOME}/log/neo4j/:/logs
    environment:
      - CEDAR_NEO4J_USER_NAME
      - CEDAR_NEO4J_USER_PASSWORD


networks:
  cedarnet:
    external:
      name: cedarnet